#
# Copyright (C) 2021 Elytrium
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[commands]
    #
    # Permissions:
    #   │
    #   └── Commands:
    #       │
    #       ├── /alert
    #       │   └── velocitytools.command.alert
    #       ├── /find
    #       │   └── velocitytools.command.find
    #       ├── /send
    #       │   └── velocitytools.command.send
    #       └── /hub
    #           ├── velocitytools.command.hub
    #           └── velocitytools.command.hub.bypass.<servername> (disabled-servers bypass permission)
    #

    [commands.alert]
        enabled = true
        prefix = "&8[&4Alert&8] &r{0}"
        message-needed = "&cYou must supply the message."
        empty-proxy = "&cNo one is connected to this proxy!"
    [commands.find]
        enabled = true
        username-needed = "&cYou must supply the username."
        player-online-at = "&6{0} &fis online at &6{1}"
        player-not-online = "&6{0} &fis not online."
    [commands.send]
        enabled = true
        console = "CONSOLE"
        not-enough-arguments = "&fNot enough arguments. Usage: &6/send <server|player|all|current> <target>"
        you-got-summoned = "&fSummoned to &6{0} &fby &6{1}"
        player-not-online = "&6{0} &fis not online."
        callback = "&aAttempting to send {0} players to {1}"
    [commands.hub]
        enabled = true
        server = "hub"
        # Set to "" to disable.
        you-got-moved = "&aYou have been moved to a hub!"
        disabled-server-message = "&cYou cannot use this command here."
        disabled-servers = [
            "foo",
            "bar"
        ]
        aliases = [
            "lobby",
            "hub"
        ]

[tools]
    [tools.protocolblocker]
        block-joining = true
        block-ping = false
        # If true, all protocols except those listed below will be blocked.
        whitelist = false
        # You can find a list of protocols here: https://wiki.vg/Protocol_version_numbers
        protocols = [
            9999,
            9998
        ]
        # For "block-ping" option.
        brand = "Version is not supported!"
        # For "block-ping", set to "" to disable.
        motd = "&cVersion is not supported!\n&ePlease, join with Minecraft 1.12.2 or newer."
        # For "block-joining" option.
        kick-reason = "&cYour version is unsupported!"
    [tools.brandchanger]
        enabled = true
        ping-brand = "YourServer 1.12.2-1.17.1"
        # For ping.
        show-always = false
        # {0} - Original server brand (e.g. Paper).
        ingame-brand = "YourServer ({0})"
    # Doesn't work with srv records.
    [tools.hostnamesmanager]
        block-joining = true
        block-ping = true
        # Connections IP logging.
        debug = false
        # For "debug" option.
        show-blocked-only = true
        # For "block-joining" option, use {DISCONNECTED} to show the default reason.
        kick-reason = "&cPlease, don't connect to the direct ip!\nUse example.com"
        whitelist = true
        # IP Addresses starting with "127." or equal to "localhost" will be blocked.
        block-local-addresses = true
        hostnames = [
            "your-domain.net",
            "your-domain.com"
        ]
        # List of IP addresses that will bypass this check.
        ignored-ips = [
            "79.555.*",
            "228.1337.*"
        ]
